using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace csharp.project_euler
{
    public class Problems
    {
        public int Problem1()
        {
            /*
                If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
                Find the sum of all the multiples of 3 or 5 below 1000.
            */

            var result = 0;

            for (int i = 0; i < 1000; i++)
            {
                if (i % 3 == 0 || i % 5 == 0)
                    result += i;
            }

            return result;
        }

        public long Problem2()
        {
            /*
                Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
                By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */

            long result = 0;

            var n1 = 0;
            var n2 = 1;
            var current = 0;

            while (current < 4000000)
            {
                current = n1 + n2;

                if (current % 2 == 0)
                    result += current;

                n1 = n2;
                n2 = current;
            }

            return result;
        }

        public int Problem3()
        {
            /*
                The prime factors of 13195 are 5, 7, 13 and 29.
                What is the largest prime factor of the number 600851475143?
            */

            var result = 0;

            var numberInQuestion = 600851475143;
            var primes = new List<int>() { 2 };

            var currentCheckValue = 2;
            var currentPossibleMaxPrime = numberInQuestion;

            while (currentCheckValue <= currentPossibleMaxPrime)
            {
                if (primes.Any(p => currentCheckValue % p == 0))
                {
                    currentCheckValue++;
                    continue;
                }

                primes.Add(currentCheckValue);

                foreach (var prime in primes)
                {
                    if (currentPossibleMaxPrime % prime == 0)
                    {
                        currentPossibleMaxPrime = currentPossibleMaxPrime / prime;
                    }
                }
                currentCheckValue++;
            }

            foreach (var prime in primes.OrderByDescending(p => p))
            {
                if (numberInQuestion % prime == 0)
                    return prime;
            }

            return result;
        }

        public int Problem4()
        {
            /*
                A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
                Find the largest palindrome made from the product of two 3-digit numbers.
            */

            var maxPalindrome = 0;
            (int i, int j) maxPalindromeCombo = (0, 0);

            for (int i = 999; i > 99; i--)
            {
                for (int j = 999; j > 99; j--)
                {
                    if (maxPalindromeCombo.i > Math.Max(i, j) && maxPalindromeCombo.j > Math.Max(i, j))
                    {
                        return maxPalindrome;
                    }
                    else
                    {
                        var product = i * j;

                        var reverseCharArray = product.ToString().ToCharArray();
                        Array.Reverse(reverseCharArray);
                        var reversedString = new string(reverseCharArray);

                        if (product.ToString() == reversedString)
                        {
                            if (product > maxPalindrome)
                            {
                                maxPalindrome = product;
                                maxPalindromeCombo.i = i;
                                maxPalindromeCombo.j = j;
                            }
                        }
                    }
                }
            }

            return maxPalindrome;
        }

        public int Problem5()
        {
            /*
                2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
                What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
            */

            var result = 1;
            var keepTrying = true;

            while (keepTrying)
            {
                // Console.WriteLine($"Currently checking on {result}");

                for (int i = 1; i <= 20; i++)
                {
                    if (result % 2520 == 0)
                    {
                        if (result % i == 0)
                        {
                            if (i == 20)
                            {
                                keepTrying = false;
                            }
                            else
                            {
                                continue;
                            }
                        }
                        else
                        {
                            result++;
                            break;
                        }
                    }
                    else
                    {
                        result++;
                        break;
                    }
                }
            }
            return result;
        }

        public int Problem6()
        {
            /*
                Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
            */

            var result = 0;
            var digitSum = 0;
            var squareOfSums = 0;
            var sumOfSquares = 0;

            for (int i = 0; i <= 100; i++)
            {
                digitSum += i;
                sumOfSquares += (i * i);
            }

            squareOfSums = digitSum * digitSum;
            result = squareOfSums - sumOfSquares;

            return result;
        }

        public int Problem7()
        {
            /*
                By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
                What is the 10001st prime number?
            */

            var currentCheckValue = 3;
            var currentPrimeNumber = 2;
            var primes = new List<int>() { 2 };
            var primeNumberCount = 1;

            while (primeNumberCount < 10001)
            {
                for (int i = 0; i < primes.Count; i++)
                {
                    if (currentCheckValue % primes[i] == 0)
                    {
                        currentCheckValue++;
                        break;
                    }
                    else
                    {
                        if (i == (primes.Count - 1))
                        {
                            currentPrimeNumber = currentCheckValue;
                            primes.Add(currentCheckValue);
                            primeNumberCount++;
                            currentCheckValue++;
                            break;
                        }
                        else
                        {
                            continue;
                        }
                    }
                }
            }

            return currentPrimeNumber;
        }

    }
}